In [1]:
import torch
import torch.nn

In [2]:
vocab = {
    '청년': 0,
    'AI': 1,
    'BIGDATA': 2,
    'NLP': 3,
    '인공지능': 4,
    'embedding': 5,
    '실습': 6
}

In [6]:
dim=10  #10차원으로 설정함 
emb_mtx = torch.nn.Embedding(len(vocab), dim)

print(emb_mtx)
print(emb_mtx.weight)

Embedding(7, 10)
Parameter containing:
tensor([[ 0.4576, -0.5561, -0.6790, -1.0846, -0.9503,  1.2458, -0.7075,  0.9787,
         -1.0094,  0.7123],
        [ 0.1781, -0.0349,  2.2479, -1.4604, -0.1961, -1.9935, -0.5591, -0.4870,
         -0.7304, -0.2380],
        [ 2.4366, -0.6242,  0.4812,  0.0895, -1.9856,  0.1118,  0.4392, -0.0199,
          0.7586, -0.1233],
        [-0.2369, -1.0782,  1.3270, -0.7903, -0.3675,  0.6443,  0.3959, -2.4920,
          0.9047,  0.6373],
        [-1.1937,  0.7116, -0.9323, -0.8343, -0.4418,  0.6526,  0.1821,  1.5994,
         -2.1765,  1.1670],
        [-0.3285,  1.0804, -0.9665, -0.3308,  0.8121, -0.3524, -0.2446, -0.2275,
          0.0163, -0.0766],
        [ 0.3428, -2.0050, -0.1374,  0.0868, -0.4670,  0.6506, -0.2829, -1.3292,
         -0.9700,  1.0056]], requires_grad=True)


In [9]:
## Practice 1 ##

# print word embedding of '청년'
idx = torch.tensor([vocab['청년']], dtype = torch.long)
# practice: make index tensor for '청년'
print("Tensor: {}\nShape: {}\n".format(idx, idx.size()))

emb = emb_mtx(idx) # make word embedding for '청년'
print("Tensor:\n{}\nShape: {}".format(emb, emb.size()))

Tensor: tensor([0])
Shape: torch.Size([1])

Tensor:
tensor([[ 0.4576, -0.5561, -0.6790, -1.0846, -0.9503,  1.2458, -0.7075,  0.9787,
         -1.0094,  0.7123]], grad_fn=<EmbeddingBackward>)
Shape: torch.Size([1, 10])


In [11]:
## Practice 2 ##

# print word embeddings for a given sentence: "청년 AI BIGDATA"
sent = ['청년', 'AI', 'BIGDATA']
idxs = []
for word in sent:
    idx = vocab[word]
    idxs.append(idx) # append idx to idxs

idxs = torch.tensor(idxs, dtype = torch.long)
print("Tensor: {}\nShape: {}\n".format(idxs, idxs.size()))

emb = emb_mtx(idxs)
print("Tensor:\n{}\nShape: {}".format(emb, emb.size()))

Tensor: tensor([0, 1, 2])
Shape: torch.Size([3])

Tensor:
tensor([[ 0.4576, -0.5561, -0.6790, -1.0846, -0.9503,  1.2458, -0.7075,  0.9787,
         -1.0094,  0.7123],
        [ 0.1781, -0.0349,  2.2479, -1.4604, -0.1961, -1.9935, -0.5591, -0.4870,
         -0.7304, -0.2380],
        [ 2.4366, -0.6242,  0.4812,  0.0895, -1.9856,  0.1118,  0.4392, -0.0199,
          0.7586, -0.1233]], grad_fn=<EmbeddingBackward>)
Shape: torch.Size([3, 10])


In [13]:
## Practice 03 ##
# construct batch level word embeddings: ["청년 AI BIGDATA", "NLP embedding 실습"]

sents = [['청년', 'AI', 'BIGDATA'],
         ['NLP', 'embedding', '실습']]

batch_idxs = []
for sent in sents:
    idxs = []
    for word in sent:
        idx = vocab[word]
        idxs.append(idx)
    batch_idxs.append(idxs)

batch_idxs = torch.tensor(batch_idxs,dtype = torch.long)
print("Tensor:\n{}\nShape: {}".format(batch_idxs, batch_idxs.size()))
print('')

emb = emb_mtx(batch_idxs)
print("Tensor:\n{}\nShape: {}".format(emb, emb.size()))

Tensor:
tensor([[0, 1, 2],
        [3, 5, 6]])
Shape: torch.Size([2, 3])

Tensor:
tensor([[[ 0.4576, -0.5561, -0.6790, -1.0846, -0.9503,  1.2458, -0.7075,
           0.9787, -1.0094,  0.7123],
         [ 0.1781, -0.0349,  2.2479, -1.4604, -0.1961, -1.9935, -0.5591,
          -0.4870, -0.7304, -0.2380],
         [ 2.4366, -0.6242,  0.4812,  0.0895, -1.9856,  0.1118,  0.4392,
          -0.0199,  0.7586, -0.1233]],

        [[-0.2369, -1.0782,  1.3270, -0.7903, -0.3675,  0.6443,  0.3959,
          -2.4920,  0.9047,  0.6373],
         [-0.3285,  1.0804, -0.9665, -0.3308,  0.8121, -0.3524, -0.2446,
          -0.2275,  0.0163, -0.0766],
         [ 0.3428, -2.0050, -0.1374,  0.0868, -0.4670,  0.6506, -0.2829,
          -1.3292, -0.9700,  1.0056]]], grad_fn=<EmbeddingBackward>)
Shape: torch.Size([2, 3, 10])
